// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Hbe7RJoWnQZ3M-wIXRXSFOzLpgZPAZU',
    appId: '1:763447493018:web:1e8a4dea755f647039ba23',
    messagingSenderId: '763447493018',
    projectId: 'messenger-9b02b',
    authDomain: 'messenger-9b02b.firebaseapp.com',
    storageBucket: 'messenger-9b02b.firebasestorage.app',
    measurementId: 'G-21D5N9F84F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUKhDKvYLQ7kFuOJnSchywBIfUdxwENdI',
    appId: '1:763447493018:android:2e27032aefc99b2a39ba23',
    messagingSenderId: '763447493018',
    projectId: 'messenger-9b02b',
    storageBucket: 'messenger-9b02b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAjvbws2vGxkyDj1KzLZRWLSWARMzS7Y0',
    appId: '1:763447493018:ios:f37dfa9051f9705f39ba23',
    messagingSenderId: '763447493018',
    projectId: 'messenger-9b02b',
    storageBucket: 'messenger-9b02b.firebasestorage.app',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAjvbws2vGxkyDj1KzLZRWLSWARMzS7Y0',
    appId: '1:763447493018:ios:f37dfa9051f9705f39ba23',
    messagingSenderId: '763447493018',
    projectId: 'messenger-9b02b',
    storageBucket: 'messenger-9b02b.firebasestorage.app',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Hbe7RJoWnQZ3M-wIXRXSFOzLpgZPAZU',
    appId: '1:763447493018:web:1f45988d9d386dc339ba23',
    messagingSenderId: '763447493018',
    projectId: 'messenger-9b02b',
    authDomain: 'messenger-9b02b.firebaseapp.com',
    storageBucket: 'messenger-9b02b.firebasestorage.app',
    measurementId: 'G-DMD3X3YHWE',
  );
}
